"""nullable transaction account ids

Revision ID: 163274bcd9df
Revises: 4cedf3848236
Create Date: 2026-08-12 14:39:58.496641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163274bcd9df'
down_revision: Union[str, Sequence[str], None] = '4cedf3848236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'from_account_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transactions', 'to_account_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'to_account_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'from_account_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
